### ISSUE TITLE
feat: render markdown with glow

### ISSUE THREAD

**Issue by h0rv** [TypicalAM/goread#42]
It would be great if we can optionally render the markdown with https://github.com/charmbracelet/glow.

**Comment by TypicalAM** [comment]
That would require adding an option to use a custom `pager`. This shouldn't be that much work, it is on my list of priorities.

**Comment by h0rv** [comment]
Cool, no promises but I will try to look into that too

**Comment by TypicalAM** [comment]
Adding support for `glow` was not possible due to it not "taking" the terminal full screen when opening, although colored output support for things like `less` and `bat` is now added (using the `PAGER` variable) via #57 

![pager](https://github.com/user-attachments/assets/8d0a1928-cbb0-4774-bd09-a530f7b15a65)
