### ISSUE TITLE
Feat: Render images instead of image urls

### ISSUE THREAD

**Issue by Banh-Canh** [TypicalAM/goread#53]
For compatible terminal emulator, such as kitty. I'm wondering how possible it is with the current design. I'm willing to take a look myself but maybe you have some pointers/ideas if it's even possible/planned.

**Comment by TypicalAM** [comment]
Most probable strategy would be to display the image in a preview popup. Image viewing support [could be added](https://github.com/charmbracelet/bubbletea/issues/163) provided that we can use something like [`kitty graphics protocol`](https://sw.kovidgoyal.net/kitty/graphics-protocol/)/[`iterm`](https://iterm2.com/documentation-images.html)/[`sixel`](https://github.com/saitoha/libsixel). When it comes to `sixel`, one should find a go implmentation because using [`libsixel`](https://github.com/saitoha/libsixel) would require `CGO` compilation which is undesirable.

 I do not have much time to dedicate to the project atm, you could take a stab at it if you want. Have a nice day!

**Comment by TypicalAM** [comment]
[This](https://www.reddit.com/r/linux/comments/t3m7zm/quick_roundup_of_bitmap_graphics_availability_in/) could also be useful
